version: "3.9"

services:
  backend:
    container_name: pc_shop_good_price-backend-1
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DEBUG=False  # Disable debug mode in production
      - WEB_ENVIRONMENT=${DB_HOST}
    command: python main.py
    restart: unless-stopped
    env_file:
      - ./backend/.env